### ISSUE TITLE
Could you explain the concept of "push-frame satellites"?

### ISSUE THREAD

**Issue by DapengFeng** [centreborelli/HDR-DSP-SR#2]
Excellent work! I have no idea, however, about push-frame satellites, since I am a beginner at satellite imagery. Could you explain the concept of "push-frame satellites"? A visual illustration is appreciated.

**Comment by gfacciol** [comment]
Thanks! Push-frame acquisitions  are illustrated here: 
https://www.eoportal.org/satellite-missions/skysat#sensor-complement (fig 36 and 37)
and here 
https://www.mdpi.com/2072-4292/12/20/3418/htm (fig 6)

The L1A images that we use in this work are taken at a much faster rate than the one illustrated in the figures. As a result the overlap between frames is much large  so the same point on the ground in seen in ~15 images. 

This article describes the different types of airborne sensors: https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=4709&context=smallsat

**Comment by DapengFeng** [comment]
Thanks for your response.

**Comment by DapengFeng** [comment]
In the crop folder, there are 2660 items. But it is unclear how to split for training and validation. The paper has 2500 sequences for training and 300 for testing.

**Comment by ngoclongct** [comment]
Hi, 
So in this project, I used 2200 first sequences to train and the next 300 sequences to test. You can use the last 160 sequences for training or testing as you wish. I don't remember if I used a specific training/validation split because in my experience, the training of our self-supervised framework is so stable and simple that I often ignore the "validation" in the case of real data. So, you can do the training/validation split as you wish or even use the last 160 sequences for validation. 
Thanks for your question.
